#
# Automagically generated by Approximatrix Simply Fortran 3.12
#
FC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\ar.exe"
WRC="C:\Program Files (x86)\Simply Fortran 3\mingw-w64\bin\windres.exe"
PRJTK="C:\Program Files (x86)\Simply Fortran 3\fwin\sfprjtk.exe"
RM=rm -f

IDIR=

LDIR=


OPTFLAGS= -g

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS=

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\example.o": ".\example.f90"
	@echo Compiling .\example.f90
	@$(FC) -c -o "build\example.o" $(FFLAGS) ".\example.f90"

clean: .SYMBOLIC
	@echo Deleting build\example.o and related files
	@$(RM) "build\example.o"
	@echo Deleting target.exe
	@$(RM) "target.exe"

"target.exe":  "build\example.o" "build\Example_Project.prj.target"
	@echo Generating target.exe
	@$(FC) -o "target.exe" -static "build\example.o" $(LDIR) $(PRJ_LFLAGS)

all: "target.exe" .SYMBOLIC

